# Generated by Django 4.2.7 on 2026-01-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_activity_ideproject_course_grade_level_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default='México', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado/Provincia'),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
    ]
