# Generated by Django 4.2.7 on 2026-01-22 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0004_add_institution_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, help_text='Número de empleado o identificador interno', max_length=50, verbose_name='ID de Empleado')),
                ('title', models.CharField(blank=True, help_text='Ej: Profesor, Ing., Lic., Dr.', max_length=100, verbose_name='Título')),
                ('specialization', models.CharField(blank=True, help_text='Área de especialización o materia', max_length=200, verbose_name='Especialización')),
                ('bio', models.TextField(blank=True, help_text='Breve descripción profesional', verbose_name='Biografía')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('office', models.CharField(blank=True, help_text='Ubicación de oficina o cubículo', max_length=100, verbose_name='Oficina')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_leave', 'Licencia'), ('suspended', 'Suspendido')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrador que creó el perfil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='editor.institution', verbose_name='Institución')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Tutor',
                'verbose_name_plural': 'Perfiles de Tutores',
                'ordering': ['institution', 'user__last_name', 'user__first_name'],
                'unique_together': {('user', 'institution')},
            },
        ),
    ]
