# Generated by Django 4.2.7 on 2026-01-22 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0006_add_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allow_late_submit',
            field=models.BooleanField(default=False, verbose_name='Permitir Entrega Tardía'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Si se especifica grupo, la actividad solo es visible para ese grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='editor.studentgroup', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Puntuación Máxima'),
        ),
        migrations.AddField(
            model_name='submission',
            name='arduino_code',
            field=models.TextField(blank=True, verbose_name='Código Arduino'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Calificación'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to=settings.AUTH_USER_MODEL, verbose_name='Calificado por'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Entrega Tardía'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_read_only',
            field=models.BooleanField(default=False, verbose_name='Solo Lectura'),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas del Estudiante'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='submission',
            name='xml_content',
            field=models.TextField(blank=True, verbose_name='Contenido XML (Blockly)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='editor.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('submitted', 'Entregada'), ('graded', 'Calificada'), ('returned', 'Devuelta')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['group', 'status'], name='editor_acti_group_i_afe34b_idx'),
        ),
    ]
