# Generated by Django 4.2.7 on 2026-03-07 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0008_reset_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('activity_new', 'Nueva actividad'), ('activity_published', 'Actividad publicada'), ('submission_graded', 'Entrega calificada'), ('group_assigned', 'Asignado a grupo'), ('info', 'Información')], default='info', max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='Enlace')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creada')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='editor.institution', verbose_name='Institución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='editor_noti_user_id_e86736_idx'), models.Index(fields=['user', 'read', '-created_at'], name='editor_noti_user_id_7043fe_idx')],
            },
        ),
    ]
