name=Servo
version=1.3.0
author=Michael Margolis, Arduino
maintainer=Arduino
sentence=Allows Arduino boards to control a variety of servo motors.
paragraph=MAX-IDE: versión compatible con ESP32 Arduino core 3.x (SOC_LEDC_TIMER_BIT_WIDTH).
category=Device Control
url=https://www.arduino.cc/reference/en/libraries/servo/
architectures=avr,megaavr,sam,samd,nrf52,stm32f4,mbed,mbed_nano,mbed_portenta,mbed_rp2040,renesas,renesas_portenta,renesas_uno,zephyr,esp32
